version: 1.0.{build}
image: Visual Studio 2019
clone_folder: c:\projects\WholeKitAndCaboodle
before_build:
- cmd: nuget restore WholeKitAndCaboodle\WholeKitAndCaboodle\WholeKitAndCaboodle.sln
build:
  project: WholeKitAndCaboodle/WholeKitAndCaboodle/WholeKitAndCaboodle/WholeKitAndCaboodle.sln
  parallel: true
  verbosity: minimal
